#!/usr/bin/python

# MIT License
#
# Copyright (c) 2020 Rik Baehnemann, ASL, ETH Zurich, Switzerland
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from mav_state_estimation.filter_imu import *

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Filter IMU data.')
    parser.add_argument('inbag_path', nargs=1, help='The bag containing the topics.')
    parser.add_argument('outbag_path', nargs=1, help='The bag to export all data to.')
    parser.add_argument('topic', nargs=1, help='The imu topic name.')
    parser.add_argument('bartlett_filter_size', type=int, nargs=1, help='The size of the filter N_B = 2**size.')

    args = parser.parse_args()

    print("Filtering rosbag: %s" % args.inbag_path[0])
    print("Filtered outbag: %s" % args.outbag_path[0])
    print("IMU topic: %s" % args.topic[0])
    print("Bartlett window size: 2**%d" % args.bartlett_filter_size[0])

    filterImu(args.inbag_path[0], args.outbag_path[0], args.topic[0], args.bartlett_filter_size[0])
